### PR TITLE
prove your pointless theme is pointless

### PR DESCRIPTION
**Pull request by louisreingold**
try installing this theme with oxygen active and see if you can get it to tell you that "ur dumb"

it won't, because the code will never run, because oxygen disables the theme system

now please stop infringing on our trademarks and copyrights and delete this project.

### CODE REVIEW

**Comment by ndawebs** [comment]
I already removed everything that generates conflicts, please if you need any more changes just request it.

**Comment by ndawebs** [comment]
The theme is principle is aesthetic, but I am also achieving in the development phase, that this can use the file functions.php that Oxygen Builder disables, I think it is essential for my way of developing for wordpress and I think I am not the only one who you need to use functions.php .. so this next week I will be uploading the changes that enable this functionality .. Thank you very much. If you need more information just ask me, I greet you with all due respect, thank you very much for your interest in my work.

**Comment by louisreingold** [comment]
It looks like you updated functions.php. I fixed the merge conflict and now you can merge it automatically.

**Comment by ndawebs** [comment]
Louis Reingold is fine, I will use the plugin that you recommended and this will be the bridge between my template and Oxygen Builder. Thank you so much! we are in contact for what you need.

**Comment by louisreingold** [comment]
🤦

**Comment by louisreingold** [comment]
Thanks for accepting my pull request!

**Pull request merged**
